### ISSUE TITLE
Package not compatible with bokeh 2.0.0

### ISSUE THREAD

**Issue by paride** [MikeWoodward/UT330B#4]
This error is printed when using bokeh 2.0.0:

```
2020-03-27 23:32:08,228 Starting Bokeh server version 2.0.0 (running on Tornado 6.0.4)
2020-03-27 23:32:08,228 User authentication hooks NOT provided (default user enabled)
2020-03-27 23:32:08,230 Bokeh app running at: http://localhost:5006/UT330BUI
2020-03-27 23:32:08,230 Starting Bokeh server with process id: 1393411
2020-03-27 23:32:08,631 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7f2e6b3b3550>: attempted to add a callback on nonexistent Button.clicks property
File "model.py", line 531, in on_change:
raise ValueError("attempted to add a callback on nonexistent %s.%s property" % (self.__class__.__name__, attr)) Traceback (most recent call last):
  File "/home/paride/.local/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 196, in run
    exec(self._code, module.__dict__)
  File "/home/paride/UT330B/UT330BUI/main.py", line 24, in <module>
    controller.setup()
  File "/home/paride/UT330B/UT330BUI/controller/controller.py", line 63, in setup
    panel.setup()
  File "/home/paride/UT330B/UT330BUI/view/settings.py", line 203, in setup
    self.connect_ut330b.on_change("clicks", self.callback_connect_ut330b)
  File "/home/paride/.local/lib/python3.8/site-packages/bokeh/model.py", line 531, in on_change
    raise ValueError("attempted to add a callback on nonexistent %s.%s property" % (self.__class__.__name__, attr))
ValueError: attempted to add a callback on nonexistent Button.clicks property
 
2020-03-27 23:32:09,153 WebSocket connection opened
2020-03-27 23:32:09,154 ServerConnection created
2020-03-27 23:32:40,793 WebSocket connection closed: code=1001, reason=None
```

It works when downgrading to bokeh 1.4.0.

**Comment by MikeWoodward** [comment]
Hi Paride, I'll fix this soon - bear with me. Mike

**Comment by MikeWoodward** [comment]
It was a problem with the button callbacks. Should be all fixed now. Works with 2.0.1.

Thank you for raising the issue Paride.
